name: e_commerce_desafio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #misc
  google_nav_bar: ^5.0.6

  #db
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  #data management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5

  #translate
  flutter_i18n: ^0.32.2

  #di
  get_it: ^7.2.0
  injectable: ^1.5.3

  #http
  dio: ^4.0.6

  #data management
  json_annotation: ^4.4.0
  dartz: ^0.10.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.1.0
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.3
  mobx_codegen: ^2.0.6

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 900

    - family: TTNormsPro
      fonts:
        - asset: assets/fonts/TTNormsProRegular.otf
          weight: 400